### ISSUE TITLE
Can't get sauron running (unexpected tIVAR ...ker_id == 0 ? '' :: @worker_id).to_s)

### ISSUE THREAD

**Issue by pellegrino** [bellmyer/sauron#1]
Hi, first of all i'ld like to congratulate the idea of this project; making my testing suite running faster is always a top priority for me :)

I'm trying to get it running in a blank rails 2.3.8 project, only with the rspec and sauron installed, and i'm having an exception inside the hydra gem that sauron uses. 

a full output is here: http://gist.github.com/512318

Am i doing something wrong? 

Thanks!

**Comment by ghost** [comment]
Hi Pellegrino-

Thanks for using Sauron! I'll take a look at your issue tonight or tomorrow, and let you know what I find.

Jaime

**Comment by bellmyer** [comment]
Hi Again-

After responding to your message, I realized I was still logged into my client's github account.  I'm Jaime Bellmyer, the creator of Sauron.

Jaime

**Comment by bellmyer** [comment]
Hello Pellegrino-

This has been fixed in the latest version of bellmyer-hydra.  Please update that gem to 0.20.12 and it should fix your issue.

Sorry, I made a small update (which had a typo in it) and made the mistake of not using the update myself.  Otherwise, I would have caught it right away.  Thanks for the heads up!

Jaime
